[tool.poetry]
name = "selenium-racing"
version = "0.1.0"
description = ""
authors = ["Abu Anubis <github@anubis.email>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
